### ISSUE TITLE
Cannot start basic example: nimterop/git 

### ISSUE THREAD

**Issue by shiMusa** [liquidev/rapid#24]
When compiling basic example, I get
`C:\Users\...\.nimble\pkgs\rapid-0.1.0\rapid\lib\glfw.nim(15, 16) Error: 
cannot open file: nimterop/git`

**Comment by lscrd** [comment]
I installed "rapid" and all its dependencies with "nimble" and I confirm that even the simplest example fails with this message. May be this is due to some incompatibility with latest version of "nimterop"?

**Comment by liquidev** [comment]
Possibly; I don't use rapid 2019 myself anymore. Prefer the latest commit, although it doesn't have some features (no audio support).

To install the latest commit (at the time of writing this), use:
```
nimble install rapid@#fc257b2
```
in your .nimble file:
```nim
requites "rapid#fc257b2"
```

**Comment by lscrd** [comment]
Thanks ! I will try the last commit.

**Comment by landgazr** [comment]
I never got this error when compiling the tests; is this a candidate for closure since it's almost a year old now using different package versions and project commit hash?

My relevant Nimble pkgs (I think):

`aglet-0.4.4  glfw-4.0.0 rapid-#3e831cb`

**Comment by liquidev** [comment]
Good point. This was never closed because I was planning to close it once a stable release had been made, which, as you can probably tell, never happened.
